version: '3'

services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: flyeagle100/frontend
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
 
